[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.25'
cache = true
force = true
optimizer = true
optimizer_runs = 200
evm_version = 'paris'

[etherscan]
sepolia = { key = "14XGE1G4VWY314CHN65RHIW3G1K449SH1N", url = "https://api-sepolia.lineascan.build/api" }

[profile.ci]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
