[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.25'
cache = true
force = true
optimizer = true
optimizer_runs = 200
evm_version = 'paris'

[profile.ci]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
